name: stickerbook_futbin_mvp
description: A minimal sticker book app that deep-links to Futbin (no scraping).

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  csv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/players.csv