name: Create Android project

on:
  workflow_dispatch:

jobs:
  create-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Create Android folder
        run: |
          flutter create .
          rm -rf lib test

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Add Android folder" || echo "No changes to commit"
          git push origin main
