name: Create Android project

on:
  workflow_dispatch:

jobs:
  create-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: Create Android folder
        run: flutter create . --project-name fut_sticker_book

      - name: Remove example lib/test (optional cleanup)
        run: |
          rm -rf lib test

      - name: Commit Android folder
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add Android folder"
          git push
