name: Fix Players CSV

on:
  push:
    paths:
      - "assets/players.csv"

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run script
        run: |
          python scripts/fix_players_csv.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/players.csv
          git commit -m "Auto-fix players.csv"
          git push
