name: Fix players.csv

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # we need history to commit back
          persist-credentials: true # keep GITHUB_TOKEN for push

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run fixer script
        run: python3 scripts/fix_players_csv.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add assets/players.csv
            git commit -m "chore: auto-fix players.csv (add imageUrl,futbinUrl)"
            git push
          else
            echo "No changes to commit."
          fi
