name: Flutter CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'        # or set a specific version like '3.19.0'

      # 🔧 Recreate a valid Android project (fixes "unsupported Gradle project")
      - name: Recreate Android project
        run: |
          rm -rf android
          flutter create . --platforms=android --project-name stickerbook_futbin_mvp --org com.example
          flutter pub get

      # (Optional) Make sure SDK levels are reasonable
      - name: Ensure Android SDK versions
        run: |
          sed -i 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 34/' android/app/build.gradle || true
          sed -i 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/' android/app/build.gradle || true

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
